export const portfolio = {
 name:'[YOUR NAME]', email:'hello@example.com', github:'https://github.com', linkedin:'https://www.linkedin.com',
 headlineLines:['I build digital','experiences','that','feel alive.'], eyebrow:'SOFTWARE ENGINEER', headline:'I build digital experiences that feel alive.', intro:'Creative development, thoughtful design, and useful technology brought together.',
 about:['I’m a software engineer with a creative streak and a soft spot for the details. I turn complicated problems into digital experiences that feel simple, useful, and a little unexpected.','My path started with helping people get technology working. Today, I bring that same patient, people-first approach to building for the web—from the interface you see to the systems behind it.','Away from the keyboard, you’ll find me exploring a new trail, sketching an idea, or taking the scenic route home.'],
 projects:[
 {id:'fieldnotes',name:'Fieldnotes',category:'PRODUCT DESIGN & DEVELOPMENT',description:'A quieter place to collect ideas. A local-first notebook that helps good thoughts find their way into the world.',tech:['React','TypeScript','Local storage'],color:'sage',image:'./assets/fieldnotes.svg',challenge:'Notes often disappear into an endless list. Fieldnotes explores how a focused writing space and simple categories can make returning to an idea feel natural.',approach:'A compact React notebook keeps drafts in browser storage. Clear empty states, keyboard-friendly controls, and a calm reading measure keep the writing in focus.',result:'The included working prototype supports creating, saving, and deleting notes on your device.',source:'./source/fieldnotes.html'},
 {id:'canopy',name:'Canopy',category:'WEB APPLICATION',description:'Every small habit grows into something. A gentle daily tracker that makes consistency feel rewarding.',tech:['React','TypeScript','CSS'],color:'blue',image:'./assets/canopy.svg',challenge:'Habit tools can turn a missed day into a failure. Canopy explores a more encouraging way to mark progress, one small action at a time.',approach:'A simple daily checklist gives immediate feedback and saves completion locally. The interface uses explicit labels and generous targets.',result:'The included prototype tracks three daily habits and keeps each day’s progress independently in browser storage.',source:'./source/canopy.html'},
 {id:'waypoint',name:'Waypoint',category:'DEVELOPER TOOL',description:'Less hunting, more helping. A searchable support toolkit that puts the right answer within reach.',tech:['JavaScript','Search','Accessibility'],color:'sand',image:'./assets/waypoint.svg',challenge:'Useful support instructions become scattered across documents. Waypoint puts a small knowledge base into one searchable, accessible view.',approach:'Instant client-side search matches titles and article text. Native disclosure elements let readers explore answers with a keyboard.',result:'The included prototype filters a small support knowledge base without a server or an account.',source:'./source/waypoint.html'}
 ],
 skills:[{name:'Frontend',items:['React & Next.js','TypeScript','Tailwind CSS','Accessible interfaces']},{name:'Backend',items:['Node.js & Express','Python','REST APIs','PostgreSQL']},{name:'Cloud & DevOps',items:['AWS','Docker','GitHub Actions','Vercel']},{name:'IT support',items:['Troubleshooting','Networking','Windows & Linux','Technical documentation']},{name:'Creative tools',items:['Figma','Framer Motion','Adobe Creative Cloud','Prototyping']}],
 experience:[{date:'2024 — PRESENT',role:'Software Engineer',company:'Independent projects',text:'Designing and developing thoughtful web experiences, from early sketches to accessible, responsive applications.'},{date:'2022 — 2024',role:'Frontend Developer',company:'Sample product studio',text:'Partnered with designers to build reusable UI components and simplify everyday product workflows.'},{date:'2020 — 2022',role:'IT Support Specialist',company:'Sample technology team',text:'Helped people solve technical problems, documented repeatable solutions, and kept essential systems running.'}]
};


