import React, {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {motion,MotionConfig,useReducedMotion,useScroll,useTransform} from 'framer-motion';
import {ArrowUpRight,ArrowDown,ArrowRight,Leaf,Menu,X,Code2,Github,Linkedin,Mail,Mountain,Monitor,Server,Cloud,Headphones,PenTool,ExternalLink} from 'lucide-react';
import {portfolio as p} from './data';
import './styles.css';

function Reveal({children,className=''}:{children:React.ReactNode,className?:string}){const reduced=useReducedMotion();return <motion.div className={className} initial={{opacity:reduced?1:0,y:reduced?0:22}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.12}} transition={{duration:.65}}>{children}</motion.div>}
function App(){
 const [menu,setMenu]=useState(false);const [selected,setSelected]=useState<number|null>(null);const dialog=useRef<HTMLDialogElement>(null);const trigger=useRef<HTMLElement|null>(null);const reduce=useReducedMotion();const {scrollY}=useScroll();const landscapeY=useTransform(scrollY,[0,900],[0,90]);const canopyY=useTransform(scrollY,[0,900],[0,40]);
 useEffect(()=>{if(selected!==null){dialog.current?.showModal();document.body.style.overflow='hidden'}return()=>{document.body.style.overflow=''}},[selected]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')setMenu(false)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]);
 const close=()=>{dialog.current?.close();setSelected(null);trigger.current?.focus()};const icons=[Monitor,Server,Cloud,Headphones,PenTool];
 return <MotionConfig reducedMotion="user"><a className="skip" href="#main">Skip to content</a><header className="nav"><a href="#home" className="logo" aria-label="Home"><Leaf size={23}/>{p.name}<span className="logo-dot">.</span></a><nav aria-label="Main navigation" className={menu?'nav-links is-open':'nav-links'} id="navigation">{['About','Work','Skills','Contact'].map(n=><a key={n} href={'#'+n.toLowerCase()} onClick={()=>setMenu(false)}>{n}</a>)}</nav><a className="hello" href={'mailto:'+p.email}>Say hello <ArrowUpRight size={17}/></a><button className="menu-toggle" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} aria-controls="navigation" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <main id="main"><section className="hero" id="home" aria-label="Introduction"><div className="scene" aria-hidden="true"><motion.img className="landscape" src="./assets/valley.webp" alt="" fetchPriority="high" style={{y:reduce?0:landscapeY}}/><motion.div className="canopy-layer" style={{y:reduce?0:canopyY}}/><div className="cloud-drift"/><div className="sunlight"/><div className="robot-idle"/><div className="screen-code">{[0,1,2,3,4].map(i=><i key={i} style={{animationDelay:`${i*.8}s`,width:`${35+i*11}%`}}/>)}</div><div className="leaves">{[0,1,2,3,4].map(i=><Leaf key={i} style={{left:`${64+i*7}%`,top:`${8+i*3}%`,animationDelay:`${i*1.2}s`}} size={12+i*2}/>)}</div></div><div className="text-wash"/><div className="hero-content"><motion.div initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.8}}><div className="eyebrow"><span/> {p.eyebrow}</div><h1>{p.headlineLines[0]}<br/>{p.headlineLines[1]}<br/>{p.headlineLines[2]} <em>{p.headlineLines[3]}</em></h1><p>{p.intro}</p><div className="hero-actions"><a className="button primary" href="#work">Explore my work <ArrowDown size={17}/></a><a className="text-link" href="#about">About me <ArrowUpRight size={17}/></a></div></motion.div></div><div className="hero-bottom"><span><span className="status-dot"/> Open to new possibilities</span><a href="#about">A little further down <ArrowDown size={15}/></a><span className="scene-caption">A little code. A little wonder.</span></div></section>
 <div className="intro-strip"><span>THOUGHTFUL BY DESIGN. CURIOUS BY NATURE.</span><div><Code2 size={16}/> Built with care <span className="strip-dot">·</span><Leaf size={16}/> Inspired by the outside</div></div>
 <section id="about" className="section about"><Reveal className="about-art"><img src="./assets/valley-detail.webp" alt="An illustrated sunlit valley, representing time spent outdoors" loading="lazy" width="600" height="700"/><div className="portrait-placeholder" role="img" aria-label="Profile photo placeholder"><Mountain size={32}/><span>Your photo goes here</span></div><span className="photo-caption">Usually building. Always exploring.</span></Reveal><Reveal className="about-copy"><div className="eyebrow">A LITTLE ABOUT ME</div><h2>Curiosity is my<br/>natural habitat.</h2>{p.about.map(t=><p key={t}>{t}</p>)}<a className="text-link" href="#contact">Let’s get to know each other <ArrowUpRight size={17}/></a></Reveal></section>
 <section id="work" className="work section"><Reveal className="section-heading"><div><div className="eyebrow">IDEAS, BROUGHT TO LIFE</div><h2>Selected work<span className="amber">.</span></h2></div><p>A few things I’ve built with purpose,<br/>patience, and plenty of curiosity.</p></Reveal><div className="projects">{p.projects.map((project,i)=><Reveal className="project" key={project.id}><button className={'project-visual '+project.color} aria-label={'Read the '+project.name+' case study'} onClick={e=>{trigger.current=e.currentTarget;setSelected(i)}}><img src={project.image} alt={project.name+' application preview'} loading="lazy" width="720" height="480"/><span className="project-open"><ArrowUpRight size={22}/></span></button><div className="project-body"><div className="eyebrow">{project.category}</div><h3>{project.name}</h3><p>{project.description}</p><div className="tags">{project.tech.map(t=><span key={t}>{t}</span>)}</div><div className="project-links"><button onClick={e=>{trigger.current=e.currentTarget;setSelected(i)}}>View project <ArrowUpRight size={16}/></button><a href={project.source} download>Source code <Github size={15}/></a></div></div></Reveal>)}</div><p className="sample-note">A collection of sample concepts, with working browser prototypes.</p></section>
 <section id="skills" className="skills-section"><div className="section"><Reveal className="section-heading"><div><div className="eyebrow">THE TOOLS IN MY BACKPACK</div><h2>A versatile toolkit.</h2></div><p>The right tools for the problem.<br/>And always room to learn something new.</p></Reveal><div className="skills-grid">{p.skills.map((s,i)=>{const Icon=icons[i];return <Reveal key={s.name} className="skill"><Icon size={26} strokeWidth={1.5}/><h3>{s.name}</h3><ul>{s.items.map(t=><li key={t}>{t}</li>)}</ul></Reveal>})}</div></div></section>
 <section className="section experience"><Reveal><div className="eyebrow">THE PATH SO FAR</div><h2>Growing through<br/>every chapter.</h2><p>Each role adds a new perspective.<br/>Here’s a sample of the journey.</p></Reveal><div className="timeline">{p.experience.map(e=><Reveal className="timeline-item" key={e.date}><span className="timeline-dot"/><div className="eyebrow">{e.date}</div><h3>{e.role}</h3><span className="company">{e.company}</span><p>{e.text}</p></Reveal>)}</div></section>
 <section id="contact" className="contact"><Reveal><Leaf size={32} strokeWidth={1.3}/><div className="eyebrow">GOOD THINGS START WITH A CONVERSATION</div><h2>Let’s make something<br/><em>worth bringing to life.</em></h2><p>Have an idea, an opportunity, or just a good trail recommendation?<br/>I’d love to hear from you.</p><a className="button cream" href={'mailto:'+p.email}>Say hello <ArrowUpRight size={18}/></a><div className="socials"><a href={p.linkedin} target="_blank" rel="noreferrer"><Linkedin size={16}/>LinkedIn <ArrowUpRight size={14}/></a><a href={p.github} target="_blank" rel="noreferrer"><Github size={16}/>GitHub <ArrowUpRight size={14}/></a><a href={'mailto:'+p.email}><Mail size={16}/>Email</a></div></Reveal></section></main><footer><a className="logo" href="#home"><Leaf size={18}/>{p.name}</a><span>© {new Date().getFullYear()} · Made with intention.</span><a href="#home">Back to the top ↑</a></footer>
 <dialog ref={dialog} aria-label={selected === null ? 'Project details' : p.projects[selected].name + ' project details'} className="project-dialog" onCancel={close} onClick={e=>{if(e.target===dialog.current)close()}}>{selected!==null&&(()=>{const q=p.projects[selected];return <><button className="dialog-close" onClick={close} aria-label="Close project"><X/></button><img src={q.image} alt={q.name+' preview'}/><div className="dialog-body"><div className="eyebrow">SAMPLE PROJECT · INTERACTIVE PROTOTYPE</div><h2>{q.name}</h2><h3>The challenge</h3><p>{q.challenge}</p><h3>The approach</h3><p>{q.approach}</p><h3>What you can try</h3><p>{q.result}</p><a className="button primary" href={q.source} target="_blank" rel="noreferrer">Launch prototype <ExternalLink size={16}/></a><a className="text-link" href={q.source} download>Download source <ArrowDown size={16}/></a></div></>})()}</dialog>
 </MotionConfig>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);



